# Generated by Django 5.1.4 on 2024-12-14 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stand_user', models.CharField(blank=True, choices=[('Jotaro Kujo', 'Jotaro Kujo'), ('Joseph Joestar', 'Joseph Joestar'), ('Jolyne Cujoh', 'Jolyne Cujoh'), ('Giorno Giovanna', 'Giorno Giovanna'), ('Josuke Higashikata', 'Josuke Higashikata'), ('Dio Brando', 'Dio Brando'), ('Koichi Hirose', 'Koichi Hirose'), ('Bruno Bucciarati', 'Bruno Bucciarati'), ('Jean Pierre Polnareff', 'Jean Pierre Polnareff'), ('Narancia Ghirga', 'Narancia Ghirga'), ('Guido Mista', 'Guido Mista'), ('Trish Una', 'Trish Una'), ('Abbacchio', 'Abbacchio'), ('Fugo', 'Fugo'), ('Rohan Kishibe', 'Rohan Kishibe'), ('Okuyasu Nijimura', 'Okuyasu Nijimura'), ('Shigechi', 'Shigechi'), ('Yukako Yamagishi', 'Yukako Yamagishi'), ('Tonio Trussardi', 'Tonio Trussardi'), ('Mikitaka Hazekura', 'Mikitaka Hazekura'), ('Yoshikage Kira', 'Yoshikage Kira')], max_length=60, null=True)),
                ('stand_name', models.CharField(max_length=30)),
                ('power', models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], max_length=1, null=True)),
                ('speed', models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], max_length=1, null=True)),
                ('range', models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], max_length=1, null=True)),
                ('durability', models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], max_length=1, null=True)),
                ('precision', models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], max_length=1, null=True)),
                ('potential', models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], max_length=1, null=True)),
                ('stand_image', models.ImageField(blank=True, null=True, upload_to='stand_images/')),
                ('user_image', models.ImageField(blank=True, null=True, upload_to='user_images/')),
            ],
        ),
    ]
