# Generated by Django 5.1.4 on 2024-12-16 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stand',
            name='stand_user',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
