# Generated by Django 5.1.4 on 2024-12-16 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_stand_stand_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stand',
            name='stand_name',
            field=models.CharField(db_index=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='stand',
            name='stand_user',
            field=models.CharField(blank=True, db_index=True, max_length=60, null=True),
        ),
    ]
